name: Benchmark
on:
  push:
    branches:
      - main

jobs:
  combine-results:
    needs: mot-metrics-benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Download all results artifacts
        uses: actions/download-artifact@v4
        with:
          path: results
      - name: Check downloaded files
        run: 'echo "Downloaded files in the results directory:"

          ls -la results/*/ || true

          '
      - id: measurement-4
        name: Record Measurement After Check downloaded files
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check downloaded files
          task: get-measurement
      - name: Combine results
        run: "touch combined_results.csv\nfor file in results/*/*; do\n  if [ -f \"\
          $file\" ]; then\n    cat \"$file\" >> combined_results.csv\n  fi\ndone\n\
          \nsort -t, -k3 -nr combined_results.csv > sorted_results.csv\ncolumn -s,\
          \ -t sorted_results.csv > pretty_results.txt\n"
      - id: measurement-6
        name: Record Measurement After Combine results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Combine results
          task: get-measurement
      - name: Show Combined Results
        run: cat pretty_results.txt
      - id: measurement-8
        name: Record Measurement After Show Combined Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Show Combined Results
          task: get-measurement
      - name: Set up Git
        run: 'git config --local user.email "yolov5.deepsort.pytorch@gmail.com"

          git config --local user.name "mikel-brostrom"

          '
      - id: measurement-10
        name: Record Measurement After Set up Git
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Set up Git
          task: get-measurement
      - name: Update README with tracker results
        run: "RESULTS_FILE=\"pretty_results.txt\"\nREADME_FILE=\"README.md\"\ncp \"\
          $README_FILE\" \"${README_FILE}.bak\"\n\ndeclare -A paper_links\npaper_links[\"\
          boosttrack\"]=\"https://arxiv.org/abs/2408.13003\"\npaper_links[\"deepocsort\"\
          ]=\"https://arxiv.org/abs/2302.11813\"\npaper_links[\"bytetrack\"]=\"https://arxiv.org/abs/2110.06864\"\
          \npaper_links[\"ocsort\"]=\"https://arxiv.org/abs/2203.14360\"\npaper_links[\"\
          strongsort\"]=\"https://arxiv.org/abs/2202.13514\"\npaper_links[\"botsort\"\
          ]=\"https://arxiv.org/abs/2206.14651\"\npaper_links[\"hybridsort\"]=\"https://arxiv.org/abs/2308.00783\"\
          \n\nnew_table=\"| Tracker | Status  | HOTA\u2191 | MOTA\u2191 | IDF1\u2191\
          \ | FPS |\\n\"\nnew_table+=\"| :-----: | :-----: | :---: | :---: | :---:\
          \ | :---: |\\n\"\n\nwhile read -r line; do\n    tracker=$(echo \"$line\"\
          \ | awk '{print $1}')\n    status=$(echo \"$line\" | awk '{print $2}')\n\
          \    hota=$(echo \"$line\" | awk '{print $3}')\n    mota=$(echo \"$line\"\
          \ | awk '{print $4}')\n    idf1=$(echo \"$line\" | awk '{print $5}')\n \
          \   fps=$(echo \"$line\" | awk '{print $6}')\n    paper_url=${paper_links[$tracker]}\n\
          \    tracker_link=\"[$tracker](${paper_url:-#})\"\n    new_table+=\"| $tracker_link\
          \ | $status | $hota | $mota | $idf1 | $fps |\\n\"\ndone < \"$RESULTS_FILE\"\
          \n\nstart_marker=\"<!-- START TRACKER TABLE -->\"\nend_marker=\"<!-- END\
          \ TRACKER TABLE -->\"\n\nawk -v start_marker=\"$start_marker\" -v end_marker=\"\
          $end_marker\" -v new_table=\"$new_table\" '\n    $0 == start_marker { print\
          \ $0; print new_table; in_table=1; next }\n    $0 == end_marker { in_table=0;\
          \ print $0; next }\n    !in_table\n' \"$README_FILE\" > temp_readme.md\n\
          \nmv temp_readme.md \"$README_FILE\"\n"
      - id: measurement-12
        name: Record Measurement After Update README with tracker results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Update README with tracker results
          task: get-measurement
      - id: check_changes
        name: Check for changes in README.md
        run: "if git diff --quiet README.md; then\n  echo \"changed=false\" >> $GITHUB_ENV\n\
          else\n  BRANCH_NAME=\"update-tracker-results-$(date +%Y%m%d%H%M%S)\"\n \
          \ echo \"BRANCH_NAME=$BRANCH_NAME\" >> $GITHUB_ENV\n  echo \"changed=true\"\
          \ >> $GITHUB_ENV\nfi\n"
      - id: measurement-14
        name: Record Measurement After Check for changes in README.md
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check for changes in README.md
          task: get-measurement
      - if: env.changed == 'true'
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: README.md
          body: This PR updates the tracker results table in the README.md.
          branch: ${{ env.BRANCH_NAME }}
          commit-message: Overwrite tracker results in README.md
          title: Overwrite tracker results in README.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  mot-metrics-benchmark:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: 'sudo apt-get update

          sudo apt-get install -y jq curl unzip

          python -m pip install --upgrade pip setuptools wheel uv

          sed -i'''' -e ''s/index = "torch-gpu"/index = "torch-cpu"/g'' pyproject.toml

          uv sync --extra yolo

          '
      - id: measurement-4
        name: Record Measurement After Install requirements
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install requirements
          task: get-measurement
      - id: cache-restore
        name: Restore MOT17 dataset cache
        uses: actions/cache@v4
        with:
          key: mot17-ablation-dataset-cache-v3
          path: boxmot/engine/TrackEval/MOT17-ablation.zip
      - if: steps.cache-restore.outputs.cache-hit != 'true'
        name: Cache MOT17.zip if not already cached
        uses: actions/cache@v4
        with:
          key: mot17-ablation-dataset-cache-v3
          path: boxmot/engine/TrackEval/MOT17-ablation.zip
      - name: Evaluation and Summarize Results
        run: "source .venv/bin/activate\n\nif boxmot eval --classes 0 --yolo-model\
          \ yolox_x_MOT17_ablation.pt --reid-model lmbn_n_duke.pt --tracking-method\
          \ ${{ matrix.tracker }} --ci --verbose --source MOT17-ablation; then\n \
          \ STATUS=\"\u2705\"\nelse\n  STATUS=\"\u274C\"\nfi\n\nif [ -f ${{ matrix.tracker\
          \ }}_output.json ]; then\n  HOTA=$(jq -r '.HOTA' ${{ matrix.tracker }}_output.json)\n\
          \  MOTA=$(jq -r '.MOTA' ${{ matrix.tracker }}_output.json)\n  IDF1=$(jq\
          \ -r '.IDF1' ${{ matrix.tracker }}_output.json)\nelse\n  HOTA=\"\"\n  MOTA=\"\
          \"\n  IDF1=\"\"\nfi\n\nmkdir -p results\nTRACKER_NAME=$(echo \"${{ matrix.tracker\
          \ }}\" | awk '{print tolower($0)}')\n\nif [ \"$STATUS\" = \"\u274C\" ];\
          \ then\n  fps=\"\"\nelse\n  declare -A tracker_fps\n  tracker_fps[\"deepocsort\"\
          ]=12\n  tracker_fps[\"bytetrack\"]=1265\n  tracker_fps[\"ocsort\"]=1483\n\
          \  tracker_fps[\"strongsort\"]=17\n  tracker_fps[\"botsort\"]=46\n  tracker_fps[\"\
          hybridsort\"]=25\n  tracker_fps[\"boosttrack\"]=25\n  fps=${tracker_fps[$TRACKER_NAME]}\n\
          fi\n\necho \"$TRACKER_NAME,$STATUS,$HOTA,$MOTA,$IDF1,$fps\" > results/${{\
          \ matrix.tracker }}.txt\n"
      - id: measurement-8
        name: Record Measurement After Evaluation and Summarize Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Evaluation and Summarize Results
          task: get-measurement
      - name: Show Results
        run: cat results/${{ matrix.tracker }}.txt
      - id: measurement-10
        name: Record Measurement After Show Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Show Results
          task: get-measurement
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.run_id }}-${{ matrix.tracker }}
          path: results/${{ matrix.tracker }}.txt
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.12'
        tracker:
          - ocsort
          - bytetrack
          - botsort
          - deepocsort
          - hybridsort
          - strongsort
          - boosttrack
    timeout-minutes: 50
permissions:
  contents: write
  pull-requests: write
