name: BoxMOT CI
on:
  push:
    branches:
      - main

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        id: measurement-start
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - name: Prepare environment variables
        run: |
          echo "tracking-methods_STATUS=${{ needs.tracking-methods.result }}" >> $GITHUB_ENV
          echo "mot-metrics_STATUS=${{ needs.mot-metrics-benchmark.result }}" >> $GITHUB_ENV
          echo "evolution_STATUS=${{ needs.evolution.result }}" >> $GITHUB_ENV
          echo "export-reid-models_STATUS=${{ needs.export-reid-models.result }}" >> $GITHUB_ENV
          echo "tests_STATUS=${{ needs.tests.result }}" >> $GITHUB_ENV
          echo "tracking-with-pose_STATUS=${{ needs.tracking-with-pose.result }}" >> $GITHUB_ENV
          echo "tracking-with-seg_STATUS=${{ needs.tracking-with-seg.result }}" >> $GITHUB_ENV
          echo "tracking-with-yolos_STATUS=${{ needs.tracking-with-yolos.result }}" >> $GITHUB_ENV

      - id: measurement-env
        name: Record Measurement After Prepare environment variables
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Prepare environment variables
          task: get-measurement

      - name: Check for failures and create summary
        run: |
          summary=""
          failed=false
          for var in $(printenv | grep '_STATUS$'); do
            job_status="${var##*=}"
            job_name="${var%%=*}"
            if [[ "$job_status" != "success" ]]; then
              summary+="$job_name failed with status: $job_status\n"
              failed=true
            fi
          done
          if [[ "$failed" = false ]]; then
            summary="All jobs succeeded."
          fi
          echo "Summary: $summary"

      - id: measurement-final
        name: Record Measurement After Check for failures and create summary
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check for failures and create summary
          task: get-measurement

      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.measurement-final.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json

  evolution:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.12"
    timeout-minutes: 50
    steps:
      - name: Start Energy Measurement
        id: evo-measurement-start
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel uv
          sed -i -e 's/index = "torch-gpu"/index = "torch-cpu"/g' pyproject.toml
          uv sync --extra yolo --extra evolve
        continue-on-error: true
        shell: bash

      - id: evo-measurement-install
        name: Record Measurement After Install requirements
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install requirements
          task: get-measurement

      - name: Evolve set of parameters for selected tracking method
        run: |
          source .venv/bin/activate
          boxmot tune --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --n-trials 3 --tracking-method strongsort --source ./assets/MOT17-mini/train --ci
        continue-on-error: true

      - id: evo-measurement-tune
        name: Record Measurement After Evolve set of parameters
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Evolve set of parameters for selected tracking method
          task: get-measurement

      - id: evo-display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.evo-measurement-tune.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json

  export-reid-models:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        id: export-measurement-start
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - uses: actions/checkout@v4

      - name: Export ReID models
        run: |
          python scripts/export_reid_models.py
        continue-on-error: true

      - id: export-measurement-final
        name: Record Measurement After Export ReID models
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Export ReID models
          task: get-measurement

      - id: export-display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.export-measurement-final.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json

  mot-metrics-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        id: mot-measurement-start
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - uses: actions/checkout@v4

      - name: Benchmark MOT metrics
        run: |
          python scripts/mot_metrics_benchmark.py
        continue-on-error: true

      - id: mot-measurement-final
        name: Record Measurement After Benchmark MOT metrics
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Benchmark MOT metrics
          task: get-measurement

      - id: mot-display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.mot-measurement-final.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
