name: Docker Image CI
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - id: extract_version
        name: Extract version from pyproject.toml
        run: 'version=$(python3 -c ''import tomllib, sys; data = tomllib.loads(open("pyproject.toml","r",
          encoding="utf-8").read()); sys.stdout.write(data["project"]["version"])'')

          echo "VERSION=$version" >> "$GITHUB_ENV"

          '
      - id: measurement-4
        name: Record Measurement After Extract version from pyproject.toml
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Extract version from pyproject.toml
          task: get-measurement
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 'boxmot/boxmot:${{ env.VERSION }}

            boxmot/boxmot:latest

            '
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
